name: logspipe

services:
  app:
    container_name: logspipe
    build:
      context: ..
      dockerfile: docker/Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/ready"]
      interval: 30s
      timeout: 2s
      retries: 3
      start_period: 40s
      start_interval: 5s
    logging:
      driver: json-file
      options:
        max-size: "3m" # Rotate logs at 3 MB
        max-file: "3"  # Keep 3 files
    ports:
      - "8088:8088"
    restart: unless-stopped

  vector:
    image: timberio/vector:0.46.1-alpine
    container_name: vector
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 100M
        reservations:
          cpus: '0.1'
          memory: 50M
    volumes:
      - ./configs/vector.yaml:/etc/vector/vector.yaml
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - app