data_dir: "/data"

sources:
  app_logs:
    type: docker_logs
    include_containers: ["logspipe"]
    auto_partial_merge: true
    
transforms:
  parse_logs:
    type: remap
    inputs: ["app_logs"]
    source: |
      # Docker logs source provides the container output in the "message" field
      # We need to parse this JSON string into structured data
      . = parse_json!(.message)

sinks:
  console:
    type: console
    inputs: 
      - parse_logs
    encoding:
      codec: json
    
  file_sink:
    type: file
    inputs: 
      - parse_logs
    path: "/data/app_logs.json"
    encoding:
      codec: json
    compression: none

  vlogs:
    inputs:
      - parse_logs
    type: elasticsearch
    endpoints:
      - https://vl.shift-1703.online/insert/elasticsearch
    api_version: v8
    compression: gzip
    healthcheck:
      enabled: false
    query:
      _msg_field: message
      _time_field: timestamp
      _stream_fields: app,env
